name: Build Java code

on:
  workflow_call:
    inputs:
      java-version:
        required: true
        type: string
      mvn-cli-opts:
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    name: Java ${{ inputs.java-version }} build
    steps:
      - name: configure git
        run: git config --global init.defaultBranch main
      # checkout the project to the runner
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2 # do not download the whole git history
          ref: ${{ github.ref }}
      - uses: ./.github/actions/init-java-repo
        with:
          java-version: ${{ inputs.java-version }}
      # build the project on the runner
      - name: Build
        run: |
          echo "Build with: mvn ${{ inputs.mvn-cli-opts }} compile"
          mvn ${{ inputs.mvn-cli-opts }} compile